safe:        false
auto:        false
server:      false
server_port: 4000
base-url:    /

source:      .
destination: ./_site
permalink: /:year/:month/:day/:title
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
permalink:   date

rdiscount:
  extensions: []
